#ifndef _LCD_CONF_H_
#define _LCD_CONF_H_


//#define ITDB02_32WD
#define ITDB02_43

#ifdef ITDB02_32WD

#define SCREEN_WIDTH		400
#define SCREEN_HEIGHT		240

#define RGB(r,g,b) ((uint16_t)(((((r)>>3)&0x1f) << 11) | ((((g)>>2)&0x3f) << 5) | (((b)>>3)&0x1f) ))

#define TLCD		LCDIFace<LCDIFaceHX8352A<SCREEN_WIDTH,SCREEN_HEIGHT>,SCREEN_WIDTH,SCREEN_HEIGHT>	
#define TLCDText	LCDText< LCDIFace<LCDIFaceHX8352A<SCREEN_WIDTH,SCREEN_HEIGHT>,SCREEN_WIDTH,SCREEN_HEIGHT>, SCREEN_WIDTH, SCREEN_HEIGHT >	

#endif

#ifdef ITDB02_43

#define SCREEN_WIDTH		480
#define SCREEN_HEIGHT		272

#define RGB(r,g,b) ((uint16_t)(((((r)>>3)&0x1f) << 11) | ((((g)>>2)&0x3f) << 5) | (((b)>>3)&0x1f) ))

#define TLCD		LCDIFace<LCDIFaceSSD1963<SCREEN_WIDTH,SCREEN_HEIGHT>,SCREEN_WIDTH,SCREEN_HEIGHT>	
#define TLCDText	LCDText< LCDIFace<LCDIFaceSSD1963<SCREEN_WIDTH,SCREEN_HEIGHT>,SCREEN_WIDTH,SCREEN_HEIGHT>, SCREEN_WIDTH, SCREEN_HEIGHT >	

#endif



#endif
